// <auto-generated />
using System;
using DataProcessorService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataProcessorService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DataProcessorService.Data.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndexWithinRole")
                        .HasColumnType("INTEGER")
                        .HasColumnName("index_within_role");

                    b.Property<string>("ModuleCategoryID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("module_category_id");

                    b.Property<string>("ModuleState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("module_state");

                    b.Property<string>("PackageID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("package_id");

                    b.HasKey("Id");

                    b.HasIndex("PackageID", "ModuleCategoryID", "IndexWithinRole")
                        .IsUnique();

                    b.ToTable("modules", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
