services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: lab-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - xmlnet

  dataprocessor:
    build:
      context: .
      dockerfile: DataProcessorService/Dockerfile
    container_name: dataprocessor
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_ENVIRONMENT=Production
      - RabbitMQ__Host=${RABBITMQ_HOST:-rabbitmq}
      - RabbitMQ__Port=${RABBITMQ_PORT:-5672}
      - RabbitMQ__Username=${RABBITMQ_USERNAME:-guest}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD:-guest}
      - RabbitMQ__QueueName=${RABBITMQ_QUEUE_NAME:-instrument_status}
    networks:
      - xmlnet

  fileparser:
    build:
      context: .
      dockerfile: FileParserService/Dockerfile
    container_name: fileparser
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_ENVIRONMENT=Production
      - RabbitMQ__Host=${RABBITMQ_HOST:-rabbitmq}
      - RabbitMQ__Port=${RABBITMQ_PORT:-5672}
      - RabbitMQ__Username=${RABBITMQ_USERNAME:-guest}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD:-guest}
      - RabbitMQ__QueueName=${RABBITMQ_QUEUE_NAME:-instrument_status}
      - FileProcessing__InputDirectory=${FILEPARSER_INPUT_DIR:-/app/input}
    volumes:
      - ./FileParserService/input:/app/input  
    networks:
      - xmlnet

networks:
  xmlnet:
    driver: bridge
